### PR TITLE
Multiple updates:

### PR DESCRIPTION
**Pull request by mwengren**
* Added platform_id, platform_name, wmo_platform_code global attrs
* Clarify use of: platform_vocabulary
* Added separate for instrument global/variable usage
* Added section on determining IOOS Asset Identifiers
* Added geophysical_variable:standard_name_uri variable attr per Derrick
* Edit/cleanup of some existing descriptions

See the rendered version [here](https://mwengren.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html).  

This contains many minor phrasing fixes, general cleanup, etc, so ideally I'd like to merge and walk back changes that need to be reverted based on today's meeting (platform_variable etc).

### CODE REVIEW

**Comment by mwengren** [comment]
@jessicaaustin @kwilcox Can I merge this in order to capture some of the description enhancements I made and we can work backwards to restore what needs to be restored based on our conversation re: `platform variable`?  

I think we need a clear description inside our own profile what the `platform_variable` must contain (trajectory_id, timeseries_id, etc) and it's role/function within CF (`cf_role` attribute etc).  It might be an identical, but shorter, description to what's in the CF docs, but I think it's necessary to spell out clearly in our own docs with examples inline and in the gold standard files.

And I'm also not sure we decided once and for all whether to include various platform attributes (such as `platform_id` and `platform_name` that I included here) as new global attributes, or to hang them off of the `platform_variable` per NCEI as they were originally.  

I've had to shift to planning the DMAC agenda so lost track of our decisions if any last week, but I do want to merge this if possible and re-edit.

**Comment by kwilcox** [comment]
Sure, merge away and edit as needed.

**Comment by mwengren** [comment]
@jessicaaustin @kwilcox @shane-axiom Latest commit includes several suggestions by Bob and some proposed changes of my own.  

Also cleanup of some attributes with missing/misleading info.  Clarified one platform per dataset and highlighted the proposed platform_variable attributes to remove in favor of their global equivalents (platform_name, platform_id, etc) - I kept these in here so they would still be visible for comparison in the [rendered version](https://mwengren.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html), but will remove next commit if there's agreement they can go.

Let me know what you think.

**Comment by mwengren** [comment]
@jessicaaustin @kwilcox @shane-axiom  I'm just going to go ahead and merge this.  I think it's a step in the right direction, but we can still revisit in a future meeting or via gh issue/email.  If you have any feedback on some of the major changes, please let me know.  

The main change is removing most of the `platform_variable` attributes - shown [here](https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html#platform-variable-to-remove) - in favor of their global equivalents - [here](https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html#platform).  This also means removing `ioos_code` from the picture.  

Also, an unresolved issue is how to handle `ioos_category` from the ERDDAP [docs](https://coastwatch.pfeg.noaa.gov/erddap/download/setupDatasetsXml.html#ioos_category).  At the moment, we make no mention of it, and we probably should.

**Pull request merged**
