### PR TITLE
Platform variable fix

### PR DESCRIPTION
**Pull request by mwengren**
Revised platform_variable:cf_role, geophysical_variable:platform, and Platform section guidance to remove explicit connection between cf_role and the 'Platform Variable'.

Suggested change for consideration.  This will allow more flexibility to attach cf_role attribute to an independent variable if a data provider chooses.

### CODE REVIEW

**Comment by ocefpaf** [comment]
The HTML diff GH action is quite verbose on a Jekyll page b/c of the timestamps updates :-/

**Comment by mwengren** [comment]
Yes, was going to ping you about that, but I see you noticed already!  Maybe there's a better solution.  Not sure why there are two comments for each commit, either.

**Comment by ocefpaf** [comment]
> Yes, was going to ping you about that, but I see you noticed already! Maybe there's a better solution. Not sure why there are two comments for each commit, either.

I'll remove these GH actions for now. They are experimental and are not really helping us here. I guess it is probably better to just focus on a draft publishing mechanism.

**Comment by ocefpaf** [comment]
See https://github.com/ioos/ioos-metadata/pull/26

**Comment by mwengren** [comment]
Rendered version of these changes is [here](https://mwengren.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html#platform).

@jessicaaustin Can you take a look at this one?  Aside from minor rewording the major change is to remove cf_role from Platform Variable.

**Pull request merged**
