### PR TITLE
Make qartod_variable:references recommended

### PR DESCRIPTION
**Pull request by jessicaaustin**

### CODE REVIEW

**Comment by mwengren** [comment]
@jessicaaustin This looks good to me.  After the comment by Nan in our standard name issue, I was worried that `references` was only a global attribute, but in fact it isn't, so we're ok to include it in both places (http://cfconventions.org/cf-conventions/cf-conventions.html#attribute-appendix). 

Looking at that though, I noticed that our guidelines list it as originating with ACDD, when in fact it's from CF.  I have a local change with that, but can you just change both the global and `qartod_variable:references` lines as part of this PR.   Have no idea why I changed one of those lines two weeks ago: https://github.com/ioos/ioos-metadata/commit/1b4e801479e1c36bb1ab708a187a883902451c49, maybe was just going for consistency with the other line that shows ACDD.

Also, I was going to respond on issue 216 to ask where we stand, since there's been a lot of discussion on adding new standard names for the next release in that repo.

**Comment by jessicaaustin** [comment]
@mwengren ok, updated. And I saw your reply to 216, that looks good. I haven't replied there because I agree with all you've said so far!

**Comment by mwengren** [comment]
great, crossing my fingers we get some confirmation on that before Feb 3: https://github.com/cf-convention/vocabularies/issues/99 - this is what I saw in passing that prompted my response.

**Review by mwengren — APPROVED** [review]
Merging, looks good.

**Pull request merged**
